// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  developer: [{ type: "autogenerated", dirName: "developer" }],
  organization: [{ type: "autogenerated", dirName: "organization" }],
  user: [{ type: "autogenerated", dirName: "user" }],
};

module.exports = sidebars;
